spring:
  application:
    name: ad-gateway
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

zuul:
  prefix: /imooc #网关前缀
  routes:
    sponsor:
      path: /ad-sponsor/** #要转发服务的path
      serviceId: eureka-client-ad-sponsor
      strip-prefix: false
    search:
      path: /ad-search/** # **匹配多级目录,任意数量字符
      serviceId: eureka-client-ad-search
      strip-prefix: false #跳过前缀